spring:
  application:
    name: autoparts-management
  datasource:
    url: jdbc:postgresql://localhost:5432/PRODADM
    username: postgres
    password: postgres
  jpa:
    openInView: true
    hibernate:
      ddl-auto: update #| create-drop | update | validate | none>
      generate-ddl: true
    properties:
      hibernate:
        jdbc.lob.non_contextual_creation: true
        show_sql: true
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
        jdbc.batch_size: 10
        order_updates: true
        batch_versioned_data: true
  sql:
    init:
      mode: always
  docker:
    compose:
      enabled: true